### ISSUE TITLE
New comment on block [block-idm181621250288]

### ISSUE THREAD

**Issue by marcus7777** [realworldocaml/book#2800]
I get :
open Core.Std;;     
Error: Unbound module Core

**Comment by naartjie** [comment]
Did you follow the [instructions](https://github.com/realworldocaml/book/wiki/Installation-Instructions)? Specifically the part:

```
opam install core
```

**Comment by naartjie** [comment]
also see #2797. I can't confirm, I'm using `4.02.3`;.

**Comment by marcus7777** [comment]
Did not install with the opam, redoing I'll test it in a minute, thank you

**Comment by marcus7777** [comment]
i still get: 
```
$ ocaml
        OCaml version 4.02.3

# open Core.Std;;
Error: Unbound module Core
```

**Comment by marcus7777** [comment]
[link to page](https://realworldocaml.org/v1/en/html/a-guided-tour.html#ocaml-as-a-calculator)

**Comment by wkwkes** [comment]
Maybe, you should use older versions such as 4.01.0

**Comment by marcus7777** [comment]
Thanks @wkwkes

**Comment by marcus7777** [comment]
Still don't work giving up trying to learn it

**Comment by agarwal** [comment]
> Still don't work giving up trying to learn it

Sorry you're having trouble. I see a few issues. First you're using `ocaml`, but as recommended in the book, you should use `utop`, a much nicer REPL. You can get utop by doing `opam install utop`.

Second, once you launch utop, you need to do `#require "core"` before doing `open Core` (since the book was published it is just `open Core` instead of `open Core.Std`).
