### ISSUE TITLE
add v2 PDF export via pandoc

### ISSUE THREAD

**Issue by gasche** [realworldocaml/book#3020]
A colleague of mine is reading Real World OCaml v1, because they found a PDF export (somewhere on the internet). If the PDF export feature is still functioning, would it be possible to publicize on the dev website a link to a v2 PDF export? They would switch to reading this new edition, which I think is preferable.

**Comment by yminsky** [comment]
That PDF export was not constructed by us, but creating one for v2 is a good idea.

**Comment by XVilka** [comment]
Maybe using something like [mdBook](https://github.com/rust-lang-nursery/mdBook) could help?

**Comment by NightMachinary** [comment]
@yminsky An epub export would also be fantastic. My eyes are very dry and I really prefer reading on an e-reader than on an iPad. E-readers also don't distract me.

**Comment by XVilka** [comment]
Seems this library can be used (and improved along the way) to produce PDF output of the book. https://github.com/johnwhitington/camlpdf

**Comment by yminsky** [comment]
I think it would be a lot easier to use pandoc or omd to output LaTeX...

**Comment by avsm** [comment]
Our plan is in two stages:

In the short term, we will:
- use pandoc to create the PDF output
- this should also unlock other backends such as ePub, since pandoc supports them out of the box.

In the medium term, we are:
- working on switching to omd once our work on the `ocaml/omd` master branch has matured sufficiently with all the extensions we use.
- add a LaTeX backend to omd
- no plan yet for ePub on this branch, so we'll figure that out separately.

**Comment by NathanReb** [comment]
You can now find a PDF version of the book here: http://dev.realworldocaml.org/book.pdf

**Comment by avsm** [comment]
need #3223 and #3224 before publicising this too widely
