### ISSUE TITLE
Replace Ulex recommendation with Sedlex

### ISSUE THREAD

**Issue by Leandros** [realworldocaml/book#3067]
Sedlex is the successor to ulex and should be preferred.

Excerpt from the sedlex project page:

> sedlex is the successor of the ulex project. Contrary to ulex which was implemented as a Camlp4 syntax extension, sedlex is based on the new "-ppx" technology of OCaml, which allow rewriting OCaml parse trees through external rewriters. (And what a better name than "sed" for a rewriter?)

(related https://github.com/realworldocaml/book/issues/1286)

**Comment by XVilka** [comment]
Quite relevant, since there is a showstopper with camlp4 on the recent OCaml versions: https://discuss.ocaml.org/t/camlp5-and-ocaml-4-08/3985/12

See the list of the packages that still depend on ulex, thus cannot be built for OCaml 4.08 and higher versions:
- beluga - created an issue [#108](https://github.com/Beluga-lang/Beluga/issues/108) for porting to sedlex
- cduce
- fstar>=0.9.5.0 - created an issue [#1792](https://github.com/FStarLang/FStar/issues/1792) for porting to sedlex
- higlo - created an issue [#3](https://github.com/zoggy/higlo/issues/3) for porting to sedlex
- kremlin - created an issue [#138](https://github.com/FStarLang/kremlin/issues/138) for porting to sedlex
- lambdoc - created an issue [#37](https://github.com/darioteixeira/lambdoc/issues/37) for porting to sedlex
-  mezzo
-  opa-base - created an issue [#196](https://github.com/MLstate/opalang/issues/196) for porting to sedlex
-  piqilib - there is an issue [#59](https://github.com/alavrik/piqi/issues/59) for porting to sedlex
-  pxp
-  sociaml-vcard - created an issue [#1](https://github.com/CREATe-centre/sociaml-vcard/issues/1) for porting to sedlex
-   wdialog
