### ISSUE TITLE
Building @runtest-all doesn't do everything @runtest does

### ISSUE THREAD

**Issue by yminsky** [realworldocaml/book#3135]
In particular, it doesn't rebuild the dune.pre files, which is often confusing.

**Comment by NathanReb** [comment]
Good point! The reason is that `mdx` only adds the `runtest-all` alias if the `.md` file contains `non-deterministic` snippets of code and the dune files generation lives under the `runtest` alias.

The name and the behaviour both are indeed confusing and I agree we should improve that. I'll report it on https://github.com/realworldocaml/mdx!
