### ISSUE TITLE
Hard to figure out what duniverse libraries are available in standalone dune examples

### ISSUE THREAD

**Issue by yminsky** [realworldocaml/book#3249]
Right now, when I'm trying to build the testing chapter, I get weird results.  For example, this test fails:

```sh dir=examples/soup_test
  $ dune runtest
  File "dune", line 3, characters 34-37:
  3 |  (libraries base stdio lambdasoup uri)
                                        ^^^
  Error: Library "uri" not found.
  Hint: try: dune external-lib-deps --missing @runtest
  [1]
```
 It can't find the uri library, even though it is available in the duniverse, as far as I can tell.  What gives?

https://github.com/realworldocaml/book/tree/testing-chapter/book/testing/examples/multi_block_expect_test

**Comment by yminsky** [comment]
Ah, I figured the main issue out here: apparently, dependencies are inferred from #require declarations in the prelude.ml.

This seems...suboptimal? It's very implicit, and really, the individual test directories are quite explicit about what they want, through their dune files. So why is this extra step necessary?

**Comment by avsm** [comment]
I think this is for the `dune` file generation, since the examples are built as completely independent dune projects.  It's not very user friendly though, I agree.

**Comment by NathanReb** [comment]
I mentioned this a few weeks ago but I think it would make sense to just write the `mdx` rules on our own rather than rely on `mdx-rule` to generate them.

It's a bit tedious but now that promotion only happens in one direction, it's also easier than it used to be. It has the advantage of making all the dependencies explicit and allows us to get rid of some of the complexity in `mdx`.

One last thing is that it's likely to look like this with dune's `mdx` stanza in the end anyway, where we'll have to explicity define the libraries, binaries and file dependencies of mdx rules so we might as well start now!

If that's fine by both of you I'm happy to take care of this right away!

**Comment by NathanReb** [comment]
Also the current generated rules aren't very dune friendly, especially the use of `progn`, so it's a good occasion to improve them!

**Comment by NathanReb** [comment]
As for the original issue of building examples, it's on my TODO! I'll look at that this week!

**Comment by avsm** [comment]
#3271 will simplify this process by adding an `(mdx)` stanza in which `(packages)` can be specified without needing to look at `prelude.ml` as we do now.
