### ISSUE TITLE
.merlin: permission denied bug

### ISSUE THREAD

**Issue by yminsky** [realworldocaml/book#3334]
I just figured out how to get this to happen. Basically, if I do a build in one of the hermetically sealed examples, it will create a .merlin file.  Then if I go and do an ordinary runtest above it, I'll get the error due to that .merlin file being unremovable, for some reason.  So now, the bug is easy to replicate.

```
[yminsky@viserion src]$ dune build
Entering directory '/home/yminsky/Documents/code/rwo/book/imperative-programming/examples/correct/dictionary'
[yminsky@viserion src]$ cd ../../..
[yminsky@viserion examples]$ dune runtest
Entering directory '/home/yminsky/Documents/code/rwo'
        dune alias book/imperative-programming/examples/dictionary (exit 1)
(cd _build/default/book/imperative-programming/examples && ../../../../install/default/bin/dune build @all @runtest --root ./correct/dictionary)
Entering directory 'correct/dictionary'
Error: exception Sys_error("src/.merlin: Permission denied")
Raised by primitive operation at file "stdlib.ml", line 324, characters 29-55
Called from file "duniverse/dune-build-info.2.5.1/src/stdune/io.ml", line
  173, characters 8-126
Re-raised at file "duniverse/dune-build-info.2.5.1/src/stdune/io.ml", line
  178, characters 8-23
Called from file
  "duniverse/dune-build-info.2.5.1/src/dune/artifact_substitution.ml", line
  407, characters 15-48
Called from file "duniverse/dune-build-info.2.5.1/src/fiber/fiber.ml", line
  229, characters 16-19
Called from file "duniverse/dune-build-info.2.5.1/src/dune/build_system.ml",
  line 1588, characters 8-1023
Called from file "duniverse/dune-build-info.2.5.1/src/fiber/fiber.ml", line
  114, characters 10-15
Re-raised at file "duniverse/dune-build-info.2.5.1/src/stdune/exn.ml", line
  37, characters 27-56
Called from file "duniverse/dune-build-info.2.5.1/src/fiber/fiber.ml", line
  85, characters 10-17
Re-raised at file "duniverse/dune-build-info.2.5.1/src/stdune/exn.ml", line
  37, characters 27-56
Called from file "duniverse/dune-build-info.2.5.1/src/fiber/fiber.ml", line
  85, characters 10-17
Re-raised at file "duniverse/dune-build-info.2.5.1/src/stdune/exn.ml", line
  37, characters 27-56
Called from file "duniverse/dune-build-info.2.5.1/src/fiber/fiber.ml", line
  85, characters 10-17

I must not crash.  Uncertainty is the mind-killer. Exceptions are the
little-death that brings total obliteration.  I will fully express my cases. 
Execution will pass over me and through me.  And when it has gone past, I
will unwind the stack along its path.  Where the cases are handled there will
be nothing.  Only I will remain.
```

**Comment by mefyl** [comment]
This is unfortunately to be expected because of the cache. Since produced artifacts are shared via hardlinks between the cache and potentially multiple build directories, they must not be altered, and write permission is thus removed. The dune maintainers estimated it was a reasonable behavior, since editing produced artifacts is spurious at best in a build system model. And since we probably don't want behavior to differ depending on whether the cache is enabled, write permission is always dropped even if the cache is disabled.

This is however usually not a problem with `.merlin` file, because they are promoted to the source tree, and promotion copies the files and restores write permission. In that case though, it seems we are building a source directory (ie a source directory in a build directory), so write permissions are indeed dropped everywhere. Here dune tries to promote merlin files from the incepted build tree to the source tree above, which is in fact a built tree too and lacks write permissions.

So far the go-to solution has been fixing the build process so that built targets are not modified. Maybe dune could skip promotion of merlin files on EACCES, potentially emitting a warning ?

**Comment by jeremiedimino** [comment]
Something's a bit off thought. The `.merlin` file is not listed as target, so it should be deleted by dune between runs. @yminsky could it be a `.merlin` file left in the source tree by an old build?

BTW, the plan is to stop generating `.merlin` files in Duned 2.7, which should be a few weeks away.

**Comment by yminsky** [comment]
That sounds like a great solution.  Let's just wait for that to land, and be done with it.  We can close this issue when that lands, I suppose.

**Comment by yminsky** [comment]
@jeremiedimino Has this landed?

**Comment by jeremiedimino** [comment]
No, it didn't make it in 2.7. The merlin side is ready, the Dune PR is ready and under review. After that, we also need to wait for OCamlLSP to upgrade its version of merlin (/cc @rgrinberg) before we can land the change to have Dune no longer generate merlin files in the source tree.

**Comment by avsm** [comment]
dune no longer generates merlin files in dune 3, so closing.
